# site settings
title: CD?L 
subtitle: Center for Digital Inquiry and Learning
email: dbecker@uidaho.edu
description: "The Center for Digital Inquiry and Learning (CDIL) is a collaboration between the College of Letters, Arts and Social Sciences (CLASS) and the University of Idaho Library. Its purpose is to advance digital scholarship opportunities at the University of Idaho."
baseurl: # the subpath of your site, e.g. /blog
url: https://cdil.lib.uidaho.edu # the base hostname & protocol for your site
author: dcnb
street_address: 850 S Rayburn Street
city: Moscow
state: ID
zip_code: 83844
country: United States of America
phone: (208) 885-6559

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/thecdil
  GitLab:
  Google-Plus: 
  LinkedIn: 
  Twitter: https://twitter.com/vandalpoem
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
